### ISSUE TITLE
Video uploads

### ISSUE THREAD

**Issue by lifenautjoe** [OkunaOrg/okuna-api#137]
Be able to upload videos to posts.

The tricky part here is that videos must be processed and this is a resource intensive operation. 

We will probably have to build some sort of pipeline for processing and optimising videos.

**Comment by shiruba** [comment]
I stumbled upon this: https://intoli.com/blog/transcoding-on-aws-lambda (maybe it helps).

**Comment by lifenautjoe** [comment]
Really cool @shiruba , thanks! We're just picking up on this.
