### ISSUE TITLE
@Mentions

### ISSUE THREAD

**Issue by lifenautjoe** [OkunaOrg/okuna-api#138]
Would be great to be able to @mention linked people. Meaning people that are following us or we are connected with.

This would prevent people from mentioning and spamming strangers while still be functional within people that are linked to each other.

**Comment by Komposten** [comment]
Maybe also allow mentioning people within a community, or at least people within the same comment chain?

**Comment by lifenautjoe** [comment]
Good point @Komposten . Would have missed this 🤦‍♂️

**Comment by tehthom** [comment]
Would this functionality be part of this issue:
Auto suggest as one starts typing @ - for example:
Typing @j would give @joel, @john, @jane - top loading names by relevance (similar to how G+ does.)

**Comment by lifenautjoe** [comment]
Definitely related. We'll first build a basic version of it which detects mentions and notifies people, up next we'll build this suggestion system.

**Comment by Komposten** [comment]
Somewhat related to this: When a post is received server-side it's a good idea to convert mentions into using the unique user ID so that the mentions are updated if the user changes username. Probably worth doing the same for community links/mentions as well.

**Comment by lifenautjoe** [comment]
Yep, that's the plan :-)
