### ISSUE TITLE
Server errors when mentioning user twice in post

### ISSUE THREAD

**Issue by lifenautjoe** [OkunaOrg/okuna-api#502]
Looks like the unique constraint on post comment mentions is failing when trying to mention a user twice under the same post.

/okuna/okuna-api/issues/824/?query=is:unresolved

**Comment by lifenautjoe** [comment]
On a comment reply, mention x one, and then mention x, together y on a consequent reply.

**Comment by lifenautjoe** [comment]
Another reported issue by Oliver, okuna/okuna-api/issues/63/?query=is:unresolved

**Comment by lifenautjoe** [comment]
Some more issues related to mentions

<img width="411" alt="image" src="https://user-images.githubusercontent.com/12737509/63688534-f4450100-c807-11e9-9fa3-f5749dcc342b.png">

**Comment by lifenautjoe** [comment]
Another issue on okuna/okuna-api/issues/63/?query=is:unresolved

**Comment by uiboy** [comment]
Confirmed with tom, this was fixed with the update 0.53, and is not happening anymore.

**Comment by uiboy** [comment]
Looks like it is still happening https://sentry.openbook.social/okuna/okuna-api/issues/10989/?query=is:unresolved

**Comment by lifenautjoe** [comment]
Dang it, I can't reproduce :-(

**Comment by uiboy** [comment]
Yea i had the same , tried so many diff ways :(
