### ISSUE TITLE
Double notifications

### ISSUE THREAD

**Issue by lifenautjoe** [OkunaOrg/okuna-api#506]
![double](https://user-images.githubusercontent.com/12737509/63583584-9613e600-c59b-11e9-8cca-34b6b2ca3354.jpg)

**Comment by uiboy** [comment]
I dont think this is a bug anymore, translated the screenshot from german, and it basically has one notification for `commented on your post` and one for `mentioned you in a comment`

I tested this with a community post and a comment with a mention to the original author..and it produces only one notification as intended.
