### ISSUE TITLE
loaddata exception when encoding new languages

### ISSUE THREAD

**Issue by javabudd** [OkunaOrg/okuna-api#512]
Using the newly added docker-compose functionality. The container does not start due to loaddata failing.

**python 3.7.3**

`pipenv run python manage.py loaddata circles.json emoji-groups.json emojis.json badges.json categories.json`

`webserver_1  |     return executor(sql, params, many, context)
webserver_1  |   File "/root/.local/share/virtualenvs/okuna-api-d_C9iZUR/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
webserver_1  |     return self.cursor.execute(sql, params)
webserver_1  |   File "/root/.local/share/virtualenvs/okuna-api-d_C9iZUR/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
webserver_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
webserver_1  |   File "/root/.local/share/virtualenvs/okuna-api-d_C9iZUR/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
webserver_1  |     return self.cursor.execute(sql, params)
webserver_1  |   File "/root/.local/share/virtualenvs/okuna-api-d_C9iZUR/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
webserver_1  |     return self.cursor.execute(query, args)
webserver_1  |   File "/root/.local/share/virtualenvs/okuna-api-d_C9iZUR/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
webserver_1  |     res = self._query(query)
webserver_1  |   File "/root/.local/share/virtualenvs/okuna-api-d_C9iZUR/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
webserver_1  |     db.query(q)
webserver_1  |   File "/root/.local/share/virtualenvs/okuna-api-d_C9iZUR/lib/python3.7/site-packages/MySQLdb/connections.py", line 226, in query
webserver_1  |     _mysql.connection.query(self, query)
webserver_1  | django.db.utils.OperationalError: Problem installing fixture '/opt/okuna-api/openbook_common/fixtures/emoji-groups.json': Could not load openbook_comm
on.EmojiGroup(pk=1): (1366, "Incorrect string value: '\\xC5\\x9Fl\\xC4\\xB1c...' for column `okuna`.`openbook_common_emojigroup`.`keyword_tr` at row 1")`

**Comment by Komposten** [comment]
This happens if the database hasn't been set to use unicode.

**Comment by lifenautjoe** [comment]
Thanks everyone! Docker change config merged :-)
