### ISSUE TITLE
Comments Count include blocked users' comments

### ISSUE THREAD

**Issue by duichwer** [OkunaOrg/okuna-api#534]
As the title says :)
See the following line for the method.
https://github.com/OkunaOrg/okuna-api/blob/f51dcfdce729223e3ec32708a56845ad07067e61/openbook_posts/models.py#L222-L237

And also check the following lines in the same files for adapting the query:
https://github.com/OkunaOrg/okuna-api/blob/f51dcfdce729223e3ec32708a56845ad07067e61/openbook_posts/models.py#L157-L158

**Other places?**
Maybe there are other places where blocked user doesn't get filtered out?

**Comment by uiboy** [comment]
Also going to fix that comment counts dont include replies yet, many users also found it odd, and showing the full count is more representative of the activity than just top level comments.
