### ISSUE TITLE
Get posts with username is slow

### ISSUE THREAD

**Issue by uiboy** [OkunaOrg/okuna-api#556]
Retrieving posts for a user with username (eg. on their profile page) is pretty slow. Needs to be optimised specially when users have many posts. For eg. test with user joel, meep or any active user.

**Comment by lifenautjoe** [comment]
Pretty sure the issue is not the amount of posts as they're all filtered first by id, but the dynamic calculation of reaction groups. We need to split the fetching of this.

**Comment by duichwer** [comment]
Even for profiles with only 24 Posts, it takes relativly long to load the profile.
