### ISSUE TITLE
is there a public okuna api? is there a list of api calls somehwere, a docu ?

### ISSUE THREAD

**Issue by michabbb** [OkunaOrg/okuna-api#576]
testing a new social platform only makes sense (for me), if there is an API. thanks!

**Comment by lifenautjoe** [comment]
Hi Micha, we have a collection of API requests in Postman here https://documenter.getpostman.com/view/5571027/S1EQSxso?version=latest , however there is no 3rd party API token so you will have to use your personal one for now.
