### ISSUE TITLE
Android app issues

### ISSUE THREAD

**Issue by BurgerhoutJ** [OkunaOrg/okuna-api#649]
Since my new Android 10 phone, I have troubles to login in the app. Or better / worser, can't login at all because errors like unknown error and no credentials found are popping up. See the screenshot. Removing and reinstalling the app is no solution.
Please help. 

![Screenshot_20191213-172238](https://user-images.githubusercontent.com/25769575/70815529-f8545900-1dcd-11ea-8eb9-1160a642f4c2.jpg)

**Comment by Komposten** [comment]
Try going to the menu (button in the bottom right) and then logging out.

If that doesn't work, go into Android settings and clear the app cache.

**Comment by BurgerhoutJ** [comment]
Cleared the app cache and now it is working. Thanks!
