### ISSUE TITLE
Waiting for server to come up...

### ISSUE THREAD

**Issue by amirali-asvadi** [OkunaOrg/okuna-api#684]
Hi,
I am trying to deploy Okuna-api on ubuntu 18.04 server and I did every step exactly as documentation said but when I tried to up-full server it got stock in Waiting for server to come up...!

<img width="566" alt="Screen Shot 2020-01-21 at 9 47 13 PM" src="https://user-images.githubusercontent.com/33135435/72831197-98d44d80-3c97-11ea-83fc-f43463c12278.png">

<img width="1064" alt="Screen Shot 2020-01-21 at 10 08 32 PM" src="https://user-images.githubusercontent.com/33135435/72832682-9d4e3580-3c9a-11ea-8e01-4805b0afe489.png">

Thanks for your help
**King regards**

**Comment by iboldurev** [comment]
Hi, @amirali-asvadi  I have such a problem too, did you manage to solve it?

**Comment by iboldurev** [comment]
I did it, you just have to wait 3-5 minutes

**Comment by lifenautjoe** [comment]
The first time the server comes up it does take a couple minutes to setup
as it downloads the docker images for all the services.

We’ll change this behavior so it streams the logs of everything that is
happening on the background.
