### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by azui999** [OkunaOrg/okuna-api#691]
![image](https://user-images.githubusercontent.com/24892321/74346432-8fe42100-4dea-11ea-91a0-718e9e19e9ff.png)

**Comment by azui999** [comment]
After startup, error is reported in the console, but it does not affect the use

**Comment by duichwer** [comment]
@azui999 are you this is related to the okuna-api and not to the website?
See https://github.com/OkunaOrg/okuna-www/issues/125

**Comment by azui999** [comment]
> @ azui999您是否与okuna-api有关，与网站无关？
> 参见[OkunaOrg / okuna-www＃125](https://github.com/OkunaOrg/okuna-www/issues/125)

I'm sorry, I sent the wrong section
