### ISSUE TITLE
Server is up. How do I get to the user interface via Browser?

### ISSUE THREAD

**Issue by dzimmerman-nci** [OkunaOrg/okuna-api#723]

**Comment by dzimmerman-nci** [comment]
I am referring to the latter: like the Okuna App, but in the web browser

**Comment by Komposten** [comment]
Okuna's web interface isn't public yet. It's being developed actively (with weekly-ish previews posted in /c/okuna in Okuna) and we're getting close to a first public version.

**Comment by dzimmerman-nci** [comment]
Will the web interface eventually be open source? Or are there any previous web interface versions available for me to check out?

**Comment by Komposten** [comment]
> Will the web interface eventually be open source? Or are there any previous web interface versions available for me to check out?

It will be open source, like all parts of Okuna. However, the source will be closed at least until the first public version is available.
There are currently no previous versions of it.

> Edit: Also, I don't think I understand where the weekly previews are posted. What is /c/okuna? I apologize for my ignorance.

c/okuna is a public community in Okuna. It's basically a public group which all Okuna users can join to discuss Okuna, see development previews from the Okuna team, ask questions, and so on. You do need an Okuna account to access it, though.

**Comment by dzimmerman-nci** [comment]
Thank you for the assistance. 

Is the old Openbook site available?

> c/okuna is a public community in Okuna. It's basically a public group which all Okuna users can join to discuss Okuna, see development previews from the Okuna team, ask questions, and so on. You do need an Okuna account to access it, though.
Gotcha. I do not have access to the beta yet.

**Comment by Komposten** [comment]
> Is the old Openbook site available?

The only Okuna-related website available is the [Okuna home page](https://okuna.io), with source code at [okuna-www](https://github.com/okunaorg/okuna-www).

**Comment by Komposten** [comment]
@dzimmerman-nci It appears that I was wrong when I said the web interface won't be available until the first public version is deployed. The Okuna web interface is now open-source and can be found in the [okuna-web](https://github.com/okunaorg/okuna-web) repository. Please note that it is still in a pre-release state, so many features (including e.g. registration) are not yet in place. Contributions are welcome! :slightly_smiling_face:
